default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: password
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: rails_blog

test:
  <<: *default
  database: rails_blog_test

production:
  <<: *default
  database: production_db_name
