default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306

development:
  <<: *default
  database: <%= ENV['DEV_DB_NAME'] %>
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  host: <%= ENV['DEV_DB_HOST'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  host: <%= ENV['TEST_DB_HOST'] %>

production:
  <<: *default
  url: <%= ENV['JAWSDB_URL'] %>
